name: CI
on: [push, pull_request]
jobs:
  TestJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building
        run: |
          cmake -S . -B build
          cd build
          cmake --build .
        working-directory: ./matrix_calculator