name: CI
on: [push, pull_request]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: cmake --build . --target matrix_calculator_LINT

  Building:
    runs-on: ubuntu-latest
    needs: [Lint]
    steps:
      - uses: actions/checkout@v3
      - name: Building
        run: |
          cmake -S . -B build
          cd build
          cmake --build .
        working-directory: ./matrix_calculator